//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeeQualifications = new HashSet<EmployeeQualification>();
        }

    
        [Key]
        public int ID { get; set; }
        public string Name { get; set; }
        public int BirthGovernorateId { get; set; }
        public int BirthNeighborhoodId { get; set; }
        public Nullable<int> CareerFieldId { get; set; }
        public string Address { get; set; }
        public Nullable<int> CompanyJobId { get; set; }
        public virtual CareerField CareerField { get; set; }
        public virtual CompanyJob CompanyJob { get; set; }
        public virtual Governorate Governorate { get; set; }
        public virtual Neighborhood Neighborhood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeQualification> EmployeeQualifications { get; set; }
    }
}
